backend:
  name: github
  repo: Watcharapol-Frong/portfolio
  branch: main
  base_url: https://decap-oauth-worker.frongbook.workers.dev
  auth_endpoint: auth

media_folder: ""
public_folder: "./"

collections:
  - name: "articles"
    label: "Articles"
    folder: "src/content/articles"
    create: true
    delete: true
    extension: "mdx"
    format: "frontmatter"
    slug: "{{slug}}"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: "./"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - { label: "Date", name: "date", widget: "date", format: "YYYY-MM-DD" }
      - label: "Sources"
        name: "sources"
        widget: "list"
        default: []
        required: false
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
      - label: "Call to Action"
        name: "cta"
        widget: "object"
        required: false
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
